"""Workspace dir management for rca_ui.

Each case gets its own dir under <workspace_root>/<case_id>/, hydrated on
first open with seed files (notes.md, draft_report.md, README.md) and a
freshly-rendered CASE.md. Idempotent: re-opening a case preserves user
edits and just re-renders CASE.md.

Design note — this module owns workspace state only. The *active session*
state (which case is open right now, transcript, lifecycle status) lives
in session_store.py. The MCP filesystem server is anchored to the path
returned by `ensure_workspace`; the agent therefore can only see/edit the
files inside that one dir.
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Seed files copied into a fresh workspace. These are *user-facing* docs
# the agent edits; AGENTS.md / .opencode/ from the legacy template are
# excluded — the rca_ui agent gets its instructions in-process via the
# OAI Agents SDK system prompt, not via a workspace file.
_SEED_FILES = {
    "README.md": (
        "# RCA case workspace\n\n"
        "This directory is the working environment for one defect-RCA case.\n"
        "Files in here are visible to the agent via the MCP filesystem tool.\n\n"
        "## Files\n\n"
        "| File | Purpose |\n|---|---|\n"
        "| `CASE.md` | case metadata (auto-rendered, do not edit directly) |\n"
        "| `notes.md` | scratchpad for cumulative observations |\n"
        "| `draft_report.md` | co-authored draft of the RCA report |\n"
    ),
    "notes.md": (
        "# Notes\n\n"
        "Cumulative observations across the RCA conversation. The agent\n"
        "appends here as facts emerge; you can also edit directly.\n\n---\n"
    ),
    "draft_report.md": (
        "# RCA Report — DRAFT\n\n"
        "## Correlation observed\n\n(...)\n\n"
        "## Mechanisms\n\n(...)\n\n"
        "## Confounders\n\n(...)\n\n"
        "## Verdict\n\n(...)\n\n"
        "## Suggested investigations\n\n(...)\n\n"
        "## Knowledge gaps\n\n(...)\n"
    ),
}

_CASE_MD_TEMPLATE = """\
# Case: {title}

| Field | Value |
|---|---|
| **Owner** | {owner} |
| **Defect type** | {defect_type} |
| **Process module** | {process_module} |
| **Scan stage** | {scan_stage} |
| **Tags** | {tags} |

## Description

{description}

---

*Auto-rendered from the CaseStudy record. To change case metadata,
PATCH the CaseStudy record via kb-api; do NOT edit this file.*
"""


def workspace_dir(workspace_root: Path, case_id: str) -> Path:
    """Path of a case's workspace dir. Pure function — does not create."""
    safe = _safe_segment(case_id)
    return workspace_root / safe


def ensure_workspace(workspace_root: Path, case_id: str, case: dict[str, Any]) -> Path:
    """Create-or-resume the workspace dir for `case_id`.

    Always re-renders CASE.md from the supplied `case` dict; preserves
    user-edited files (notes.md, draft_report.md) on resume."""
    dest = workspace_dir(workspace_root, case_id)
    dest.mkdir(parents=True, exist_ok=True)

    for name, body in _SEED_FILES.items():
        target = dest / name
        if not target.exists():
            target.write_text(body, encoding="utf-8")

    (dest / "CASE.md").write_text(_render_case_md(case), encoding="utf-8")
    _ensure_git_repo(dest)
    return dest


def _render_case_md(case: dict[str, Any]) -> str:
    tags = case.get("tags") or []
    return _CASE_MD_TEMPLATE.format(
        title=case.get("title") or "(untitled)",
        owner=case.get("owner") or "(unknown)",
        defect_type=case.get("defect_type") or "(unspecified)",
        process_module=case.get("process_module") or "(unspecified)",
        scan_stage=case.get("scan_stage") or "(unspecified)",
        tags=", ".join(tags) if tags else "(none)",
        description=case.get("description") or "",
    )


def _safe_segment(case_id: str) -> str:
    """case_id from AutoCRUD is `case-study:<uuid>` — colons are valid on
    POSIX but trip up some tooling, so we collapse to a flat-name."""
    return case_id.replace(":", "_").replace("/", "_")


def _ensure_git_repo(dest: Path) -> None:
    """`git init` + seed commit so file-tree tooling has something to
    enumerate. Idempotent."""
    if not (dest / ".git").exists():
        try:
            subprocess.run(
                ["git", "init", "-q", "-b", "main"],
                cwd=dest,
                check=True,
                capture_output=True,
            )
        except (FileNotFoundError, subprocess.CalledProcessError) as exc:
            logger.warning("git init failed for %s: %s", dest, exc)
            return

    head_check = subprocess.run(
        ["git", "rev-parse", "--verify", "-q", "HEAD"],
        cwd=dest,
        capture_output=True,
    )
    if head_check.returncode == 0:
        return

    env = {
        "GIT_AUTHOR_NAME": "rca-ui",
        "GIT_AUTHOR_EMAIL": "rca-ui@local",
        "GIT_COMMITTER_NAME": "rca-ui",
        "GIT_COMMITTER_EMAIL": "rca-ui@local",
    }
    try:
        subprocess.run(["git", "add", "-A"], cwd=dest, check=True, capture_output=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "seed workspace", "--allow-empty"],
            cwd=dest,
            check=True,
            capture_output=True,
            env={**os.environ, **env},
        )
    except subprocess.CalledProcessError as exc:
        logger.warning("seed commit failed: %s", exc.stderr or exc)


def archive_workspace(dest: Path, archive_path: Path) -> None:
    """tar.gz the workspace into `archive_path` (used at session close
    for cheap-resume + audit trail). Idempotent overwrite."""
    archive_path.parent.mkdir(parents=True, exist_ok=True)
    base = archive_path.with_suffix("").with_suffix("")  # strip .tar.gz
    shutil.make_archive(str(base), "gztar", root_dir=str(dest))
