"""Workspace seeding — populate active_dir with template files + rendered CASE.md.

Called by workspace_lifecycle.open_workspace() in two situations:

  - First-time open (no prior workspace_archive): copy entire template tree
    into the empty active_dir.
  - Resume open (workspace_archive untar'd already): re-run defensively to
    fill in any missing template files (e.g. user deleted README.md). User
    edits in mutable files (notes.md, draft_report.md) are preserved by
    the "skip if exists" rule.

In BOTH cases CASE.md is always overwritten — case metadata in CaseStudy is
the authoritative source; users edit it via AutoCRUD PATCH on the case
record, not by editing CASE.md inside the workspace.

opencode.json is intentionally NOT in the template — opencode config is
injected via env vars at spawn time (see services.opencode_config) so the
agent cannot self-modify its own constraints.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from rca.domain.case_study import CaseStudy

# Template tree lives at <repo>/templates/case_workspace/
_TEMPLATE_DIR = Path(__file__).resolve().parents[3] / "templates" / "case_workspace"


def seed_workspace(case: CaseStudy, dest_dir: Path) -> None:
    """Populate `dest_dir` with the case workspace skeleton.

    Idempotent on resume: existing files are kept (preserving user edits),
    missing template files are added, CASE.md is always re-rendered."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    _copy_template_tree(_TEMPLATE_DIR, dest_dir)
    (dest_dir / "CASE.md").write_text(_render_case_md(case), encoding="utf-8")


def _copy_template_tree(src: Path, dst: Path) -> None:
    """Recursively copy `src` into `dst`, skipping any file that already
    exists at the destination. Mirrors `shutil.copytree(dirs_exist_ok=True)`
    semantics but with a per-file "skip if exists" guard so user edits in
    notes.md / draft_report.md survive a defensive second seed."""
    for entry in src.iterdir():
        target = dst / entry.name
        if entry.is_dir():
            target.mkdir(exist_ok=True)
            _copy_template_tree(entry, target)
        elif not target.exists():
            shutil.copy2(entry, target)


def _render_case_md(case: CaseStudy) -> str:
    """Render CASE.md content from CaseStudy fields. Optional fields render
    as "(unspecified)" rather than literal "None"."""
    return _CASE_MD_TEMPLATE.format(
        title=case.title,
        description=case.description,
        owner=case.owner,
        defect_type=case.defect_type or "(unspecified)",
        process_module=case.process_module or "(unspecified)",
        scan_stage=case.scan_stage or "(unspecified)",
        tags=", ".join(case.tags) if case.tags else "(none)",
    )


_CASE_MD_TEMPLATE = """\
# Case: {title}

| Field | Value |
|---|---|
| **Owner** | {owner} |
| **Defect type** | {defect_type} |
| **Process module** | {process_module} |
| **Scan stage** | {scan_stage} |
| **Tags** | {tags} |

## Description

{description}

## RCA flow

See `AGENTS.md` for the workspace orientation and
`.opencode/agents/rca-agent.md` for the 9-step flow.

## Output files in this workspace

- `notes.md` — your scratchpad (cumulative observations)
- `draft_report.md` — the report you and the agent co-author
- `uploaded_final_report.md` — present only if you uploaded a draft for
  co-finalization

---

*This file is auto-rendered from the CaseStudy record on every
open-workspace. To change case metadata, PATCH the CaseStudy record via
the API; do NOT edit this file directly (your edits will be lost).*
"""
